version: 0.2
phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package
      - dir target
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/course-service.jar
  discard-paths: yes
